### ISSUE TITLE
How it work

### ISSUE THREAD

**Issue by Xcpro24** [benmoose39/YouTube_to_m3u#47]
Can you show me how it work with local computer??

I tried to run it but error

**Comment by benmoose39** [comment]
can you paste/attach the error messages here?

**Comment by Xcpro24** [comment]
> 

I have try it in github n it work already
Now i try this link https://m.vidio.com/live/205-indosiar it cannot run
Why??
Can u try that link?

**Comment by benmoose39** [comment]
please note that the script is intended for YouTube live channels only.

**Comment by Xcpro24** [comment]
Okay thank you
