### ISSUE TITLE
Two Live Feed

### ISSUE THREAD

**Issue by naveenland4** [benmoose39/YouTube_to_m3u#7]
Hi Bro,

If we have two live feed how to select which feed to be viewed in the m3u8 file?

Ex: Sky News by default Covid Live is picked, but the 2nd Live feed is the news coverage. How do we select the news coverage here?

https://www.youtube.com/user/skynews

TIA

**Comment by benmoose39** [comment]
There is a unique video id for every video. The link can be given as:
https://www.youtube.com/watch?v=X_uOlJPyd1s
https://www.youtube.com/watch?v=9Auq9mYxFEE
respectively.

**Comment by naveenland4** [comment]
Thanks. But it tried the link like..

https://www.youtube.com/watch?v=9Auq9mYxFEE

and

https://www.youtube.com/watch?v=9Auq9mYxFEE/live

But unfortunately the video (either the one) doesn't play using these links

**Comment by benmoose39** [comment]
https://www.youtube.com/watch?v=9Auq9mYxFEE : this link is there in my playlist, and it fetches the m3u as well.

**Comment by benmoose39** [comment]
the script fetches m3u8 from the page source.

**Comment by naveenland4** [comment]
Thanks but unfortunately that doesn’t play

**Comment by benmoose39** [comment]
Just checked the link again and found out that it doesn't play in vlc. But with other players including tivimate and kmplayer, there are no issues. I don't think people would use vlc in their TV to watch live channels.
