### ISSUE TITLE
Add Claro Sports 1, 2, 3 and 4. The official channel of the Olympic games in Hispanic America

### ISSUE THREAD

**Issue by sdgrs546547Q** [benmoose39/YouTube_to_m3u#8]
Hello. I would like you to add Claro Sports channels to your m3u list, they are the ones that give the Olympic games in Hispanic America.
Claro Sports 1: https://youtu.be/pQONlmOhXeg
Claro Sports 2: https://youtu.be/51iVn2QqGLY
Claro Sports 3: 
https://youtu.be/tQ4FuUCmsOM
Claro Sports 4: https://youtu.be/QlMUZM5sWkg

Thank you very much 👍

**Comment by benmoose39** [comment]
Hey..
These channels are geo-restricted, so I would suggest that you run the script locally. For any help, feel free to DM on Discord

**Comment by sdgrs546547Q** [comment]
thanks for the information friend. I need to run that script 24/7 or I can rut it only one time?

**Comment by benmoose39** [comment]
When you run the script, you get a link that is valid for the next 5-6 hours. If you can, run it 24/7, or leave it running only when you watch tv.
